const actionTypes = Object.freeze({
  //allcode
  FETCH_TOY_SUCCESS: 'FETCH_TOY_SUCCESS',
  FETCH_TOY_FAILED: 'FETCH_TOY_FAILED',

  FETCH_ALLCODES_BY_TYPE_SUCCESS: 'FETCH_ALLCODES_BY_TYPE_SUCCESS',
  FETCH_ALLCODES_BY_TYPE_FAILED: 'FETCH_ALLCODES_BY_TYPE_FAILED',

  FETCH_TOY_BY_ID_SUCCESS: 'FETCH_TOY_BY_ID_SUCCESS',
  FETCH_TOY_BY_ID_FAILED: 'FETCH_TOY_BY_ID_FAILED',

  UPDATE_TOY_SUCCESS: 'UPDATE_TOY_SUCCESS',
  UPDATE_TOY_FAILED: 'UPDATE_TOY_FAILED',

  FETCH_ALL_TOY_SUCCESS: 'FETCH_ALL_TOY_SUCCESS',
  FETCH_ALL_TOY_FAILED: 'FETCH_ALL_TOY_FAILED',
});

export default actionTypes;
