const actionTypes = Object.freeze({
  //allcode
  FETCH_TOY_SUCCESS: 'FETCH_TOY_SUCCESS',
  FETCH_TOY_FAILED: 'FETCH_TOY_FAILED',

  FETCH_ALLCODES_BY_TYPE_SUCCESS: 'FETCH_ALLCODES_BY_TYPE_SUCCESS',
  FETCH_ALLCODES_BY_TYPE_FAILED: 'FETCH_ALLCODES_BY_TYPE_FAILED',

  FETCH_TOY_BY_ID_SUCCESS: 'FETCH_TOY_BY_ID_SUCCESS',
  FETCH_TOY_BY_ID_FAILED: 'FETCH_TOY_BY_ID_FAILED',

  UPDATE_TOY_SUCCESS: 'UPDATE_TOY_SUCCESS',
  UPDATE_TOY_FAILED: 'UPDATE_TOY_FAILED',

  FETCH_ALL_TOY_SUCCESS: 'FETCH_ALL_TOY_SUCCESS',
  FETCH_ALL_TOY_FAILED: 'FETCH_ALL_TOY_FAILED',

  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILED: 'LOGIN_FAILED',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  LOGOUT_FAILED: 'LOGOUT_FAILED',
  //get Userinfo with token

  GET_USER_INFO_SUCCESS: 'GET_USER_INFO_SUCCESS',
  GET_USER_INFO_FAILED: 'GET_USER_INFO_SUCCESS',

  //rehresh token
  REFRESH_TOKEN_SUCCESS: 'REFRESH_TOKEN_SUCCESS',
  REFRESH_TOKEN_FAILED: 'REFRESH_TOKEN_FAILED',

  //add item to cart
  ADD_ITEM_TO_CART_SUCCESS: 'ADD_ITEM_TO_CART_SUCCESS',
  ADD_ITEM_TO_CART_FAILED: 'ADD_ITEM_TO_CART_FAILED',
  //get cart by userid
  FETCH_CART_BY_USER_ID_SUCCESS: 'FETCH_CART_BY_USER_ID_SUCCESS',
  FETCH_CART_BY_USER_ID_FAILED: 'FETCH_CART_BY_USER_ID_FAILED',

  //delete item from cart
  DELETE_ITEM_FROM_CART_SUCCESS: 'DELETE_ITEM_FROM_CART_SUCCESS',
  DELETE_ITEM_FROM_CART_FAILED: 'DELETE_ITEM_FROM_CART_FAILED',

  //pay item from cart
  PAY_ITEM_FROM_CART_SUCCESS: 'PAY_ITEM_FROM_CART_SUCCESS',
  PAY_ITEM_FROM_CART_FAILED: 'PAY_ITEM_FROM_CART_FAILED',
});

export default actionTypes;
